getlago/lago-go-client

subscription.go

We want to add the ability to choose to bill users at subscription date anniversary and not only on a calendar basis.
The objective of this pull request is to add the support for `billing_time` attribute for subscription creation
Possible values will be `anniversary` and `calendar`
The changes are :
- Accept the new `billing_time` argument into 'POST /subscriptions'
This PR follows:
- https://github.com/getlago/lago-api/pull/352 to update the subscription data model.
- https://github.com/getlago/lago-api/pull/360 to add a new date service for invoice bounds
- https://github.com/getlago/lago-api/pull/364 to expose billing time into GraphQL
- https://github.com/getlago/lago-api/pull/365 to expose billing time into API

feat: Allow billing_time attribute for subscription creation

---

charge.go
plan.go

This PR attempt to fix the charge edition when updating a plan. The `LagoID` field was missing.

feat(charge): Fix edition of charge on plan update

---

billable_metric.go

The objective of this feature is to introduce a system of persistent billable metrics that do not resume to 0 at the end of a billing period.
This PR adds the support for the new `recurring_count_agg` aggregation type

feat(persisted-metrics): Add support for recurring count aggregation

---

error.go
subscription.go

Wrong copy past on my previous PR, my bad.
Added a check on type assert to avoid panic, had to implem the missing method to satisfy error type interface (it's a bit unusual to have to do this but it's the fastest way without reworking all the error system).

fix(subscription): wrong resty Result struct on GetList

---

subscription.go

This PR is adding support for the following attributes on Subscription:
- `previous_plan_code`
- `next_plan_code`
- `downgrade_plan_date`

feat: Add previous and next attributes on Subscription

---

subscription.go

To get the creation of subscriptions to work with Lago's latest updates, the ExternalID needs to be added to the SubscriptionInput struct.

Add ExternalID to SubscriptionInput

---

subscription.go

Saw that it was on the input but not on the subscription object like in the doc, unless I'm mistaken 👍

fix(subscription): missing ExternalID

---

subscription.go

Spotted this change, maybe it still works with external_customer_id but it makes more sense with the external_id and follow the doc.

fix(subscription): use externalID on Subscription Terminate following API change

---

subscription.go

This PR adds support for `subscription_date` param when creating or updating subscription

feat (subscriptions): add support for subscription date param

---

event.go

According to https://doc.getlago.com/docs/api/events/metered-event#arguments `external_subscription_id` should exist in the client.

feat(events): Add ExternalSubscriptionID to event params

---

subscription.go

We were using `externalID` as a body parameter for the `DELETE /subscriptions` endpoint instead of using `DELETE /subscriptions/:external_id

fix(subscription): Terminate is using externalId in the route

---

billable_metric.go

👉  https://github.com/getlago/lago/issues/32
We want to be able to price differently billable metrics according to several dimensions (groups).
For example, creating a `storage` pricing based on the `region of the server` and the `cloud provider` used.
This PR adds `group` on `billable_metric`.

feat(groups): Add group on billable metric

---

charge.go
group.go
plan.go

👉  https://github.com/getlago/lago/issues/32
We want to be able to price differently billable metrics according to several dimensions (groups).
For example, creating a `storage` pricing based on the `region of the server` and the `cloud provider` used.
This PR adds documentation for:
- `group_properties` on `charge` creation
- `GET billables_metrics/:code/groups` endpoint

feat(groups): Add group_properties on charge and groups endpoint

---

customer.go
organization.go

👉  https://github.com/getlago/lago/issues/99
The goal of this PR is to move fields related to Billing or Invoice into `billing_configuration`.
For customer: `vat_rate`.
For organization: `invoice_footer`, `vat_rate`.

misc: Move fields to billing configuration

---

README.md
credit_note.go

👉  https://github.com/getlago/lago/issues/59
The objective of this feature is to introduce a new concept of credit notes.
The main reason behind this need is to handle the following case:
- If an overdue has been paid because a customer passes from a yearly plan to a monthly plan (`in_advance`), we charge the customer as if the remainder does not exist.
This PR adds the credit note API clients
Related to https://github.com/getlago/lago-api/pull/505

feat(credit_notes): Add Credit note API client

---

invoice.go

👉  https://github.com/getlago/lago/issues/99
When a billing period is over, users don’t want to invoice straight away.
They want a defined number of days to:
- Collect delayed events for usage
- Adjust invoice amounts for items
The goal of this PR is to rename `invoice#status` to `invoice#payment_status`.
`invoice#status` will be used to define if the invoice is `draft` or `finalized`.
**⚠️ This is a breaking change PR, do not merge before Dec. 8th.**

feat(grace_period): Rename invoice#status to payment_status

---

add_on.go
billable_metric.go
coupon.go
credit_note.go
customer.go
error.go
group.go
invoice.go
lago.go
organization.go
plan.go
subscription.go
wallet.go
wallet_transaction.go

As described in @Koumbaya comment [here](https://github.com/getlago/lago-go-client/pull/38#discussion_r1044545988), this implements safe type assertion everywhere in your package. I choose that this should return a HTTP422 error but feel free to suggest me another code (maybe HTTP500) which will do the trick for you guys!
There might be a way to enforce this policy with the linter by the way. 👍

feat(assert): safe type assertion

---

coupon.go
customer.go
organization.go
subscription.go
wallet.go

👉  https://github.com/getlago/lago/issues/61
It’s impossible to bill a customer following its own timezone.
Lago ingests events, creates subscription boundaries and trigger invoices on a UTC timezone, which is the same for everyone.
This feature adds the possibility to choose the timezone an organization or a customer should be billed in.
This PR adds:
- Support for timezone at customer level
- Support for timezone at organization level
- Replace `expiration_date` by `expiration_at` on coupons
- Replace `expiration_date` by `expiration_at` on wallets

feat(timezones): Update clients to support customer timezones

---

billable_metric.go

👉  https://github.com/getlago/lago/issues/179
As a user, I want to be able to delete a billable metric that is linked to a subscription in case of a change of pricing (e.g. we no longer charge customers based on the number of API calls).
Once deleted, the corresponding charges will be removed from the plans and from all draft invoices.
Deleted metrics will still be included in past invoices (i.e. finalized invoices).
The goal of this PR is to add on the billable metric response:
- `activeSubscriptionsCount`
- `draftInvoicesCount`
These fields are used to know the impact of deleting billable metric.

feat(delete_bm): Update response for billable metric deletion

---

customer.go

Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete customers.
The goal of this feature is to be able to soft-delete a customer linked to an active or terminated subscription.
This PR adds the new customer destroy route

feat(delete_customer): Add the destroy customer route

---

coupon.go

**Context**
Currently, there is no way to delete objects linked to a subscription. This can be a real limitation during PoCs and onboarding, as users have to ping us to delete customers.
The goal of this feature is to be able to soft-delete an applied coupon.
**Description**
This PR adds the destroy endpoint for applied coupon.

feat(delete_coupon): Ability to destroy an applied coupon

---

billable_metric.go

This PR fixes creating and updating billable metrics. Per the [docs](https://doc.getlago.com/docs/api/billable_metrics/create-billable-metric), create and update requests for Billable Metrics are to be wrapped with `{"billable_metric": <metric>}`, however the existing client sends `{<metric>}` in the POST body.

fix create/update billable metrics

---

credit_note.go
fee.go
invoice.go

👉  https://github.com/getlago/lago/issues/149
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR adds a new route to retrieve a single fee via the API (`GET /api/v1/fees/:id`)
Related to https://github.com/getlago/lago-api/pull/866

feat(instant_charge): Add API route to show a fee

---

billable_metric.go
charge.go

Plans edition has some issue if you update some properties of a billable metric, especially if you change groups definition or aggregation type :
"After the billable metric edition, new dimensions are created with new group_id that do not match the ones in the plans already defined"
This PR exposes a new `plans_count` field in the `BillableMetric` response type to let the API users know if the BM is editable.
Related to https://github.com/getlago/lago-api/pull/914

feat(bm): Expose count of attached plans

---

customer.go
organization.go

Fixes https://github.com/getlago/lago-go-client/issues/62
Fields mapping for addresses fields was wrong. Mapping was defined with `address_line_X` when json is actually sending `address_lineX`

fix: Addresses field mapping

---

wallet.go

The wallet input fields weren't added to the request body. This fixes it.

add wallet input object to create wallet request

---

event.go
fee.go

👉  https://getlago.canny.io/feature-requests/p/instantly-charge-the-customer-when-an-event-is-processed
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR adds the new `POST api/v1/events/estimate_fees` route
Related to https://github.com/getlago/lago-api/pull/923

feat(instant_charge): Add event estimate fees route

---

charge.go
plan.go

👉  https://github.com/getlago/lago/issues/149
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR allows having an instant charge.

feat(instant_charge): Ability to define charge as instant

---

fee.go

👉  https://getlago.canny.io/feature-requests/p/instantly-charge-the-customer-when-an-event-is-processed
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR adds:
- Definition for `GET /api/v1/fees`
- Definition for `PUT /api/v1/fees/:id`
- Add new fields definition to fees:
- lago_invoice_id
- external_subscription_id
- payment_status
- created_at
- succeeded_at
- failed_at
- refunded_at
- …

feat(instant_charge): Expose fees updapte and get all routes

---

event.go

Currently it's required to use strings as values when sending events but using aggregates with usage based metrics it's required to send them as integer or float otherwise the values are ignored.
CURL example from Lago itself where properties "hours" sent as integer.
```
curl --location --request POST "https://lago.instance.com/api/v1/events" \
--header "Authorization: Bearer $__YOUR_API_KEY__" \
--header 'Content-Type: application/json' \
--data-raw '{
"event": { 
"transaction_id": "__UNIQUE_ID__", 
"external_subscription_id": "__EXTERNAL_SUBSCRIPTION_ID__",
"external_customer_id": "__EXTERNAL_CUSTOMER_ID__", 
"code": "fra01.xeon.e1200v6.64", 
"timestamp": $(date +%s), 
"properties":  { 
"hours": 12
}
}
}'
```

fix: allow using other data types as int/float for property values

---

plan.go

When using omitempty, the field isn't sent to the API at all when its the golang default value. 
bool -> false
int -> 0
This causes issues on the Lago API since `pay_in_advance` and `amount_cents` are required fields in the json. I think that is a issue on other Input structs as well.

fix: Sending default values when creating plans to API

---

invoice.go

This PR adds the missing filters and fields on the invoice client.
Missing filters:
- external_customer_id
- status
- payment_status
Missing fields:
- invoice_type
- credit_amount_cents
- credit_amount_currency
- total_amount_cents
- total_amount_currency

feat(invoice): Add missing fields and filters

---

charge.go
fee.go
plan.go

👉  https://getlago.canny.io/feature-requests/p/define-minimum-fees
We want to allow users to set spendings minimum on usage-based charges.
The goal of this PR is to:
- add min_amount_cents to Charge
- add lago_true_up_fee_id to Fee
- add lago_true_up_parent_fee_id to Fee

feat(min_charge): Ability to specify a minimum amount for a charge

---

coupon.go

Prevent issue with percentage_rate as it is serialized as string but it is a float value

fix(coupon): percentage rate is received a string

---

invoice.go

Update `Invoice` definition:
- `currency`
- `fees_amount_cents`
- `coupons_amount_cents`
- `credit_notes_amount_cents`
- `sub_total_vat_excluded_amount_cents`
- `sub_total_vat_included_amount_cents`
- `prepaid_credit_amount_cents`
- `legacy`
- `amount_currency`
- `vat_amount_currency`
- `credit_amount_currency`
- `total_amount_currency`
- `amount_cents`
- `credit_amount_cents`

feat(invoice): Refactoring on invoice amounts

---

applied_tax_rate.go

👉  [https://getlago.canny.io/feature-requests/p/create-several-tax-rates](https://getlago.canny.io/feature-requests/p/create-several-tax-rates)
Currently, tax can be set individually either on the customer or the organization level. However, it’s not possible to define a global tax tag that can be reusable everywhere.
The goal of this PR is to be able to add the AppliedTaxRate resource.

feat(tax_rates): Add applied tax rate resource

---

coupon.go

Similar to https://github.com/getlago/lago-go-client/pull/85 also the status query param is currently wrongly constructed to do extra quotation marks `"` which land in the query string url escaped.
By removing the excessive json tag 
```diff
- /applied_coupons?status=%22active%22
// turns into
+ /applied_coupons?status=active
```

Fix ListAppliedCoupons Status filter

---

.github/workflows/golangci-lint.yml
go.mod
go.sum
lago.go
webhook.go

this MR adds a Webhook util to:
- fetch the webhook public key 
- validate that a given signature is signed with the aforementioned key
closes #95

feat: add webhook

---

credit_note.go
customer.go
fee.go
invoice.go
organization.go
tax.go

👉  [https://getlago.canny.io/feature-requests/p/create-several-tax-rates](https://getlago.canny.io/feature-requests/p/create-several-tax-rates)
Currently, tax can be set individually either on the customer or the organization level. However, it’s not possible to define a global tax tag that can be reusable everywhere.
The goal of this PR is to add:
- The Tax object
- The relation between taxes and organization
- The relation between taxes and customers
- The relation between taxes and invoices
- The relation between taxes and fees
- The relation between taxes and credit notes

feat(taxes): Add tax resources

---

credit_note.go
fee.go
invoice.go

Today, all tax rates are exposed as `float` in Lago API but the current openapi file define them as `string`. 
The current PR fixes it by removing the `string` fields mapping.

fix(tax): Tax rates are exposed as number not as string

---

error.go
webhook.go

Current Error struct does not match format of the API sent by the API
The API format is:
```json
{
"status": 422, 
"error": "Unprocessable Entity",
"code": "validation_errors", 
"error_details": {
"code": ["value_already_exist"]
}
}
```
while the current implementation is expecting:
```json
{
"status": 422, 
"message": "Unprocessable Entity",
"error_details": ["value_already_exist"]
}
```
This PR updates the struct tags to ensure error received from the API are correctly parsed

fix: API error Unmarshaling

---

charge.go

This PR is adding the missing `volume`  charge model to the list of accepted charge model for charge creation and update
Fixes https://github.com/getlago/lago-go-client/issues/111

fix(charge): Add missing volume charge model

---

tax.go

This is to make it possible to set 0% tax rate while creating a tax 
to fix https://github.com/getlago/lago-go-client/issues/119

fix: accept 0% as tax rate

---

tax.go

Fixes my previous pull request:
- Accept 0% as tax rate input 
- throw error when the tax rate is not provided

fix: accept 0% as tax rate & throw error when rate not provided

---

add_on.go

Applied add on have been deprecated since it has been replaced by the invoice creation route.
Related to https://github.com/getlago/lago-api/pull/1282
This PR removes the routes related to the applied add-ons

feat(add_on): Remove routes for applied add on creation

---

coupon.go

Call to `GET /v1/api/coupons/:code` is missing the `terminated_at` value
This PR is adding the missing field in the `V1::CouponSerializer`

fix(coupon): Add missing coupons#terminated_at

---

billable_metric.go
event.go

For metrics that are charged upon a time frame, Lago is not able to calculate correctly the charge. For instance, imagine you want to price the number of GB/seconds used by a server. Currently, you can either calculate the number of seconds used, or the number of Gigabytes used, but not both at the same time.
This PR adds:
- the new `Event#timestamp` format with miliseconds precision
- The new `weighted_sum_agg` aggregation value in the `BillableMetric#aggregation_type` enumeation
- The new `BillableMetric#weighted_interval` enum

feat(weighted-sum): Add weighted sum fields to billable metric

---

add_on.go
charge.go
fee.go
invoice.go
plan.go

Add a custom name to display on invoice for subscription fee and charges
When generating an invoice, don't display the name of the plan or the name of the billable metrics to the customer.

feat(invoice_display_name): Add invoice display name

---

subscription.go

We want to improve the way we are overriding a plan. Without working as a duplicate, by adding the logic for managing parent and children of plans.
The goal of this PR is to add the endpoint `GET /api/v1/subscriptions/:external_id`.

feat(override-plan): Ability to fetch a single subscription

---

subscription.go

Hey lago devs,
After digging around a bit and a conversation with one of your devs this bug was found.
This prevented us from creating subscriptions in the newest version of this client. because it wanted to send a PlanOverridesInput along without any actual values.
Omitempty only omits the field if the value in that field is a nil value. unfortunately an empty struct does not count as a nil value.
(direct quote from the docs "The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.")
By making it a pointer we make sure that the value is a nil pointer and thus is omitted from the request.
A recommendation is to have any values …

made PlanOverridesInput struct in the SubscriptionInput a pointer

---

coupon.go

Originally spawned by this Roadmap item: https://getlago.canny.io/developer-experience/p/add-couponname-to-appliedcoupon-object the `List all applied coupons` endpoint now exposes the `coupon_name` but the property is still missing in the golang `AppliedCoupon` type.
This PR adds the `coupon_name` to the `AppliedCoupon` type and makes it accessible to the user

feat(coupon): Add CouponName property to AppliedCoupon

---

fee.go

Hi team,
I have noticed a change in the PreciseUnitAmount field of the Fees object that used to be an int, but has been changed to a string in one of your last updates. This broke our invoicing flow so I've made a PR!

replace PreciseUnitAmount type string to int

---

event.go

Per [docs](https://docs.getlago.com/api-reference/events/event-object#:~:text=of%20event%20reception.-,properties,-object) it is an object that can contain value as string or number, and this will match in the same as in [`EventInput`](https://github.com/getlago/lago-go-client/blob/main/event.go#L25)

fix(events): mark properties as object rather than string

---

organization.go

Before, it was not possible to adapt document number. With this feature it will be enabled to switch between `per_customer` and `per_organization` document numbering logic. Also, it will be possible to edit number prefix.
This PR adds support for new document numbering fields

feat (document-numbering): add support for document numbering fields

---

lago.go

- Allow `Queryparams` on `client.delete()`

fix(client): Allow queryparams on client delete

---

billable_metric.go
customer.go
wallet.go
webhook.go
webhook_endpoint.go

Occurred on multiple endpoints: 
- [billable_metric.go](https://github.com/getlago/lago-go-client/compare/main...cedricgautier:lago-go-client:fix/impossible-errors?expand=1#diff-0d9a1ea59d7ed3edd991b64be61a4eee9d64c8b93c3578f14e8b6d267e4d6881)
- [customer.go](https://github.com/getlago/lago-go-client/compare/main...cedricgautier:lago-go-client:fix/impossible-errors?expand=1#diff-c2441d20bf2078144decc89c9af4bebb5e5674ea5e606ab3d888b9e34efd2c60)
- [wallet.go](https://github.com/getlago/lago-go-client/compare/main...cedricgautier:lago-go-client:fix/impossible-errors?expand=1#diff-8f13b0d9924fdfa71f814f67ed2fe52040f50d5112485ec4c3ee068c6c605658)
- [webhook.go](https://github.com/getlago/lago-go-client/compare/main...cedricgautier:lago-go-client:fix/impossible-errors?expand=1#diff-6d78887239bed …

Fix errors : Fix impossible condition, nilness on error check

---

plan.go
subscription.go

👉  https://getlago.canny.io/feature-requests/p/set-minimum-spend-for-subscriptions
As a user, I want to define the minimum spend that applies to the customer's plan. Consider the following monthly plan:
- Subscription fee = $50 per month (in arrears);
- Usage-based charge = $10 per unit per month (in arrears); and
- Monthly minimum spend = $100.
If at the end of the month, the customer has consumed 3 units, their total invoice will be: $50 + 3 * $10 = $80 + $20 (true-up fee) = $100.
This PR adds minimum commitment to plan and plan overrides.

feat(minimum-commitment): Add minimum commitment

---

README.md

Simply updates the mentioned version on the readme for easier copying, especially now that a major version has been hit, I think it makes sense to update the version number there.
And by specifying `@v1` in the readme everyone who copies it will get the latest version that is available at that time without the need to always update it further

Update Lib Version in Readme

---

billable_metric.go
charge.go
customer.go
fee.go
plan.go
subscription.go

Lago is not currently supporting more than 2 levels of event grouping (parent → children)
The goal of this feature is to allow more flexibility of event grouping by allowing an unlimited level of grouping and making it easier to define default charge properties for events based on their properties.
This PR is related to https://github.com/getlago/lago-openapi/pull/210
It adds the new filter fields in both input and output objects

feat(filter): Add filter fields

---

wallet_transaction.go

We want to differentiate a free wallet transaction vs. a paid wallet transaction.
And be able to void some wallet transactions.
This PR aims to add the `transaction_status` field for Wallet.

feat(wallet): Add transaction_status to wallet object

---

wallet_transaction.go

We want to differentiate a free wallet transaction vs. a paid wallet transaction.
And be able to void some wallet transactions.
This PR aims to rename:
- `paid` to `purchased`
- `offered` to `granted`
for the `transaction_status` field for Wallet.

feat(wallet): Rename transaction statuses for wallet

---

wallet_transaction.go

We want to differentiate a free wallet transaction vs. a paid wallet transaction.
And be able to void some wallet transactions.
This PR aims to create a voided wallet transaction.

feat(wallet): Add voided_credits to WalletTransaction

---

wallet.go

After the release of real-time wallet version 1, some customers have expressed concerns about odd or missing behaviors.
The goal of this PR is to rename `Wallet#rule_type` into `Wallet#trigger`.

feat(wallet): Rename wallet rule_type into trigger

---

wallet.go

👉 https://getlago.canny.io/feature-requests/p/define-a-target-balance-to-reach-for-recurring-top-up
We want to allow users to top-up their wallets to reach a specific target balance.
We can currently define a fixed top-up but we want to add the ability to specify a dynamic top-up (target balance to reach).
The goal of this PR is to add:
- `method`
- `target_ongoing_balance`
- `started_at`
to `recurring_transaction_rule`

feat(wallet): Add method and target_ongoing_balance to recurring_transaction_rule

---

error.go
error_test.go

before: `lago.Error` is not assignable to regular go `error`

feat: implement error interface

---

customer.go

- Since update on groups, `lagoId` is no more a `uuid` for groups on usage

fix(customers): Fix lagoId type for groups usage

---

error.go
error_test.go

This pull request adds support for multiple error details returned from the Lago API. When you use the batch endpoint, it's possible that Lago returns multiple validation errors. This could not be unmarshalled to the Error struct. 
This fixes #174

fix: Add support for multiple errors

---

invoice.go

👉 https://getlago.canny.io/feature-requests/p/regroup-invoices-to-generate-one-payment-intent
We want to be able to group invoices to generate one payment.
Today we don't track payment terms and do not mention whether a payment or an invoice is overdue.
The goal of this PR is to add:
- `payment_overdue`
to `invoice`

feat(dunning): Add payment_overdue to invoice

---

customer.go

This PR adds support for shipping address that will be used in tax integrations.

feat (customers): add support for shipping address

---

gross_revenue.go
invoice_collection.go
invoiced_usage.go
mrr.go
wallet.go

In Go, when a string attribute is explicitly noted at `string` for serialization, outer quotes are added `"`. I have no idea if it's intentional, but probably.
Typically, the `WalletListInput.ExternalCustomerID` will result in this URL:
```
/api/v1/wallets?external_customer_id=%22julien%22
```
Hence, the external_id we look for the DB is `"julien"`, not `julien`.
```sql
SELECT
"customers".*
FROM
"customers"
WHERE
"customers"."deleted_at" IS NULL
AND "customers"."organization_id" = "external_id"
AND "customers"."external_id" = "\"julien\""
LIMIT 1
```
```go
package main
import (
"encoding/json"
"fmt"
)
type Interesting struct {
Quoted    string `json:"quoted,omitempty,string"`
NotQuoted string `json:"not_quoted,omitempty"`
}
func main() {
strings := Interesting{"lago", "lago"} …
```

fix(inputs): Fix string encoding as paramters

---

overdue_balance.go

👉 https://getlago.canny.io/feature-requests/p/regroup-invoices-to-generate-one-payment-intent
We want to be able to group invoices to generate one payment.
Today we don't track payment terms and do not mention whether a payment or an invoice is overdue.
The goal of this PR is to add an analytics endpoint for fetching overdue balances per month and per currency at the customer or organization level.

feat(analytics): Add overdue balance endpoint

---

charge.go
plan.go

See https://github.com/getlago/lago-api/pull/2232

feat(charges): Add Charge.RegroupPaidFees

---

payment_request.go

See https://github.com/getlago/lago-api/pull/2420

feat(dunning): Add payment requests endpoint (get list)

---

invoice.go
plan.go
subscription.go
usage_threshold.go

AI companies want their users to pay before the end of a period if usage skyrockets. The problem being that self-serve companies can overuse their API without paying, triggering lots of costs on their side.
This PR adds:
- New `ProgressiveBillingCreditAmountCents` attribute to `Invoice` struct
- New `InvoiceCreditItemType` values (`invoice` and `credit_note`)
- New `UsageThreshold` and `UsageThresholdInput` structs
- New `UsageThreshold` attribute to `Plan` and `PlanInput` structs

feat(ProgressiveBilling): Expose Usage Threshold fields

---

fee.go

For some customers some amounts are not enough precise as Lago convert fees to `amount_cent`.
Add precise amounts to fee object.

feat(precise-amounts): Add precise amounts to fee object

---

lifetime_usage.go

AI companies want their users to pay before the end of a period if usage skyrockets. The problem being that self-serve companies can overuse their API without paying, triggering lots of costs on their side.
This PR adds new routes to fetch and update the lifetime usage of a subscription

feat(ProgressiveBilling): Expose lifetime usage GET and PUT

---

customer.go

We currently only create Lago customers as **companies**, but there is a need to support both **companies** and **individuals**. This change is motivated by scenarios where customers may be a mix of B2B and B2C, and where external integrations require handling both **Contacts** and **Companies**.
To address this, we are introducing a new field, `customer_type`, to distinguish whether a customer is a **company** or an **individual**. Existing customers will remain unaffected with `customer_type` set to the default `nil`. 
This PR adds `firstname`, `lastname` and `customer_type` to the customer object and customer input.

feat(customer-type): Add customer type, firstname and lastname to customer

---

charge.go
event.go

AI, CPaaS and Fintech customers can apply a price to a unit that fluctuates over time. Currently Lago does not support this usecase.
This PR is related to https://github.com/getlago/lago-api/pull/2610.
It documents the new `precise_total_amount_cents` in input and result payloads on `POST /api/v1/events` and `POST /api/v1/batch_events`

feat(DynamicPricing): Expose Event#precise_total_amount_cents

---

customer.go

This PR fixes issue related to customer input payload for both update and create as well for Customer type.
In both cases, the `firstname` and `lastname` fields were not serialized correctly as they were sent as `first_name` and `last_name` and so were ignored by the API

fix(customer): Firstname and Lastname must be sent as firstname and lastname

---

billable_metric.go

This PR is related to https://github.com/getlago/lago-api/pull/2704
It exposes:
- The new `expression` field on billable metric input and output payloads
- The new `POST /api/v1/billable_metrics/evaluate_expression` api end-point

feat(felixible aggregation): Expose expression in API

---

invoice.go

The error details API returns an object rather than a simple string:

fix: parse InvoiceErrorDetail.details as an object correctly

---

billable_metric.go
plan.go
tax.go

The API response are returning a lot of counters. Since the exposed resources can be linked to a lot of objects and can be called a lot, these counters are posing a scalability problem and are slowing down the global performance of the API.
To remediate the situation the decision was made to remove all these fields.
This PR removes the following fields:
- BillableMetric
-  active_subscriptions_count
- draft_invoices_count
- plans_count
- Plan
- active_subscriptions_count
- draft_invoices_count
- Tax
- add_ons_count
- charges_count
- customers_count
- plans_count

misc: Remove *_count fields

---

customer.go
invoice.go

Add info about invoice-custom-sections related udpates

Feat(invoice_custom_sections): update go-client with invoice_custom_sections

---

payment_request.go

Fix for https://github.com/getlago/lago-go-client/issues/223
The API is expecting an `external_customer_id`, but the documentation is inconsistent, as it exposes a `customer_external_id` field

fix(paymentRequest): requires an external_customer_id

---

customer.go

Updated the current_usage method to accept an optional apply_taxes parameter, defaulting to True. This parameter is included in the query string as a lowercase string ("true" or "false").

feat: add apply taxes params to current usage

---

customer.go

This PR adds the missing `provider_payment_methods` field in the `CustomerBillingConfiguration` and `CustomerBillingConfigurationInput` types

fix(customer): Add support for provider payment methods

---

plan.go

**Describe the bug:**
The `PlanInput` struct's `bill_charge_monthly` field uses the singular form, while the Lago API expects the plural form `bill_charges_monthly`, as documented in [https://docs.getlago.com/api-reference/plans/create#body-plan-bill-charges-monthly](https://docs.getlago.com/api-reference/plans/create#body-plan-bill-charges-monthly) and the list plan endpoint. This discrepancy causes issues when creating or retrieving plans.
**Expected behavior:**
The `PlanInput` struct should use the plural form `bill_charges_monthly` to align with the Lago API.
**- Actual:**
```go
BillChargeMonthly bool `json:"bill_charge_monthly"`
```
**- Expected:**
```go
BillChargesMonthly bool `json:"bill_charges_monthly"`
```
**Changes:**
* Renamed the `BillChargeMonthly` field in the `PlanInput` …

fix: plan input request of bill charges monthly

---

wallet.go

remove `omitempty` from walletTransactionRules on WalletInput

Fix: wallets update - do not nullify empty array on recurring_tranasction_rules

---

customer.go

Currently, setting `PeriodsCount` in the `PastUsage` method throws a marshaling error because it's typed as int in JSON.
```
json: cannot unmarshal number into Go value of type strin
```
Added the `,string` json tag which should turn the `PeriodsCount` into a string so that it can be Unmarshalled into `map[string]string`.

fix: customer past usage period count json type

---

payment_receipt.go
payment_request.go

Adds the missing Meta pagination to payment requests and payment receipts 
https://docs.getlago.com/api-reference/payment-receipts/get-all
https://docs.getlago.com/api-reference/payment-requests/get-all

fix: add meta pagination payment receipt, payment request

---

invoice.go

The [`retry_payment` endpoint on api](https://github.com/getlago/lago-api/blob/bcdea346d54c6aa6c648c35ff08095aa7e2dee39/app/controllers/api/v1/invoices_controller.rb#L156-L164) **does not return** an invoice object. 
The explanation for this is due [the payment for that invoice will be retried asynchronously](https://github.com/getlago/lago-api/blob/fe159417fc15ae48b4eab94641a32a30ef39ac11/app/services/invoices/payments/retry_service.rb#L32) and the invoice information may change. With that in mind, we may be returning an out-dated record, so is preferred to return nothing. 
We kept the method signature with Invoice as an expected return to be consistent with other endpoints and to not add a breaking change right now.

fix(invoices):retry_payment does not return an invoice

---

.github/workflows/gofmt.yml
.github/workflows/golangci-lint.yml
billing_entity.go
credit_note.go
organization.go
payment.go
wallet.go
wallet_transaction.go

This PR runs `gofmt` on all Go files in the project and adds a GitHub Actions workflow to ensure that `gofmt` is run on every push and pull request.
I wasn't sure whether to create a new workflow or add a new job within the existing workflow. I can update it if needed.
The new workflow was tested within https://github.com/getlago/lago-go-client/pull/257/commits/fde6b39208fbad7eb598f0892fbd61c9f40123f0:

chore(lint): Run `go fmt` on all Go files and add `gofmt` to CI

---

alert.go

This field was added after alerting support was added to this client: https://github.com/getlago/lago-openapi/pull/380

fix(alert): Expose TriggeredAlert.CustomerExternalID

---

event.go
event_test.go

This PR improves the Event().Batch() signature to replace `*[]EventInput` and `*[]Event` with `[]EventInput` and `[]Event`

fix(events): Improve batch events handling

---

event_test.go
invoice.go
invoice_test.go
utils.go

This PR fixes the `Invoice().GetList()` client to match the Lago Rest API
NOTE: for now `metadata` filter is not supported as it requires some changes in the handling of the query parameters

fix(invoice): Improve GetList input

---

coupon_test.go
credit_note_test.go
invoice_test.go
testing/testing.go

This moves the `HandlerFunc` into a `testing` package to avoid returning it as part of our public API.

misc(testing): Move `HandlerFunc` into a `testing` package

---

subscription.go
subscription_test.go

This is related to https://github.com/getlago/lago-api/pull/4047.

feat(subscription): Allow to skip invoice on subscription termination

---

api_log_test.go
coupon_test.go
credit_note_test.go
event_test.go
invoice_test.go
subscription_test.go
testing/testing.go

This simplifies the way we manage server mocking by defining a `testing.MockServer` struct which includes a DSL to easily define assertions on request.
Instead of:
```go
server := lt.HandlerFunc(c, mockResponse, func(c *qt.C, r *http.Request) {
c.Assert(r.Method, qt.Equals, "GET")
c.Assert(r.URL.Path, qt.Equals, "/api/v1/applied_coupons")
query := r.URL.Query()
c.Assert(query.Get("external_customer_id"), qt.Equals, "CUSTOMER_1")
c.Assert(query.Get("status"), qt.Equals, "active")
c.Assert(query.Get("per_page"), qt.Equals, "10")
c.Assert(query.Get("page"), qt.Equals, "1")
c.Assert(query["coupon_code[]"], qt.DeepEquals, []string{"BLACK_FRIDAY", "CYBER_MONDAY"})
})
defer server.Close()
client := New().SetBaseURL(server.URL).SetApiKey("test_api_key")
result, err := …
```

test: Simplify test setup

---

subscription.go
subscription_test.go
testing/testing.go

This is related to https://github.com/getlago/lago-api/pull/4026.

feat(subscription): Allow refund as part of the subscription termination credit note

---

feature.go
lago.go
plan.go
plan_entitlements.go
subscription.go
subscription_entitlements.go

Tested with local scripts, making actual calls. I'm not too convinced with the mocked test so haven't committed them.

Add Entitlements support

---

api_log_test.go
coupon_test.go
credit_note_test.go
customer.go
customer_test.go
error_test.go
event_test.go
invoice_test.go
payment_request_test.go
subscription_test.go
wallet_transaction_test.go

This PR follows a critical issue on the `GET /api/v1/invoices` when requests were filtered by `external_customer_id` from the GO SDK client. See https://github.com/getlago/lago-go-client/pull/288
A new set of endpoints have been added to retrieve resources scoped to a specific customer.
This PR adds the clients for all the newly created routes:
- `/api/v1/customers/:customer_external_id/applied_coupons`
- `/api/v1/customers/:customer_external_id/credit_notes`
- `/api/v1/customers/:customer_external_id/invoices`
- `/api/v1/customers/:customer_external_id/payment_requests`
- `/api/v1/customers/:customer_external_id/payments`
- `/api/v1/customers/:customer_external_id/subscriptions`
- `/api/v1/customers/:customer_external_id/wallets`
Related to:
- …

feat(customers): Add new routes scoped to customers

---

customer.go
customer_test.go

A customer belongs to a single billing entity and cannot change its currency. So it does not make sense to filter customer resources by `billing_entity_ids` or `currency`.
This removes those unnecessary filters.

fix(customer): Remove unnecessary filters on customer scoped routes

---

wallet.go
wallet_test.go

👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
Follow up of https://github.com/getlago/lago-api/pull/4282.
This adds a `transaction_name` to the wallet transaction recurring rule types that are then used to populate the name of the triggered wallet transactions.

feat(wallet-transaction): Add `transaction_name` to wallet transaction rules

---

wallet.go
wallet_test.go

👉  https://getlago.canny.io/feature-requests/p/define-the-name-of-a-wallet-transaction-at-top-up
Follow up of https://github.com/getlago/lago-api/pull/4327.
This allows to provide a `name` for the wallet transactions created when creating a wallet via the `transaction_name` field.

feat(wallet): Allow to set the name of a wallet's initial transactions

---

plan.go

When creating a plan, a new interval option should be available: `semiannual`.

feat(semiannual): Add semiannual interval
