customer.go
- Add customers listing endpoints support
=> feat(customers): Add index and show on API

subscription.go
Add `name` support for `subscription`
=> fix(subscription): Add name support

invoice.go
- `EventsCount` and `Units` were missing
=> fix(invoices): Add missing InvoiceFee properties

billable_metric.go
https://doc.getlago.com/docs/api/billable_metrics/billable-metric-object
=> feat(billable_metric): add missing fields

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
Add templates for issues and feature requests
=> misc: Update issue template

fee.go
=> misc(fees): Add fees date boundaries

wallet.go
Expose wallet balance in cents for align with last updates on API
=> feat: Output wallet balance in cents

subscription.go
Related to https://github.com/getlago/lago-api/pull/1013
=> feat(subscription): Allow plan filters on subscription index

customer.go, organization.go
Expose new tax_identification_number attribute on customer and organization model
=> feat: add tax_identification_number to customer and organization

coupon.go
This PR adds the coupon's description attribute now available
=> feat: add description field to coupons

webhook.go
this PR adds a ValidateBody function to WebhookRequest.
=> Add ValidateBody to WebhookRequest

subscription.go
This PR adds 2 improvements
You can now delete a pending subscription by passing a status=pending as query param
You can now filter GET /subscriptions by passing an array of status as query param
=> feat(subscription) allow to pass status to index and delete

customer.go, invoice.go, organization.go
This PR exposes the new `net_payment_term` on orga, customer, and invoice.
Also show the new `payment_due_date` on invoices
=> feat: handle new net-payment attribute

charge.go
The objective of this feature is to introduce a new graduated percentage charge model similar to the current graduated charge model but applying a rate to the units rather than an amount.
This PR documents the new fields related to the `graduated_percentage` charge model
=> feat(charge): Add graduated percentage charge model

customer.go
Some of our users want to retrieve usage in the past. The main problem they are facing is that at the beginning of a new period, they cannot compute usage in third party systems, or see if everything went well as usage for the past period has been removed.
This PR adds a new route to fetch the past_usage for a customer/subscription.
=> feat(past_usage): Expose route to fetch customer past usage

event.go
On the path for high volume improvements, we need to adapt the structure of the events table for better performance.
This PR:
- Adds the missing Event.Get route
- Updates the Event.Create to return the created event
=> feat(event): Update event client

credit_note.go
Add route for https://github.com/getlago/lago-api/pull/1412
=> feat(credit-note): Add estimate route before creation

event.go
This adds a result struct, otherwise, it will throw an error.
=> fix(events): add result to Create and EstimateFees

customer.go
- Add `checkout_url` endpoint support for `customers`
=> feat(customers): Add checkout_url endpoint

gross_revenue.go, invoiced_usage.go, mrr.go, outstanding_invoice.go
=> feat(analytics): Add analytics resources

invoice_collection.go
Rename outstanding invoices to invoice collection
=> misc(analytics): Rename outstanding invoices to invoice collection

customer.go
Add payment_provider_code to customer's billing configuration.
=> feat(psp-accounts): Add payment_provider_code

invoice.go
This PR adds support for generating invoice payment url
=> feat(invoice-payment-url): add support for generating invoice payment url

subscription.go
- Add Update (PUT) Method on `subscriptions`
=> fix(subscriptions): Add Update Method (PUT)

subscription.go
`Subscription.TrialEndedat` was added with the Trial Improvements feature.
https://github.com/getlago/lago-openapi/pull/216
=> feat(subscriptions): Add TrialEndedAt attribute

customer.go
Change `integration_customer` param to `integration_customers`
=> misc: Change integration_customer param to integration_customers

customer.go
This PR updates integration customer definition based on the logic logic for removal integration customer objects
=> feat (integration-customers): update integration customer definition

fee.go
See https://github.com/getlago/lago-api/pull/2233
=> feat(fee): Add Delete capability

wallet.go, wallet_transaction.go
See https://github.com/getlago/lago-api/pull/2336
=> feas: add invoice require successful payment

wallet.go, wallet_transaction.go
add wallet transaction metadata added on this pr getlago/lago-api#2406
=> feat(wallet): add metadata to wallet transaction

payment_request.go
See https://github.com/getlago/lago-api/pull/2426
=> feat(dunning): Add create payment requests endpoint

customer.go, invoice.go
add Invoice.ErrorDetails and /retry endpoint
=> feature(anrok): add error details to invoie response

event.go, lago.go
This PR adds the support for the future ingest API for events on Lago US cluster.
Support for EU cluster and self-hosted will come later
=> feat(event): Add support for ingest API

customer.go, organization.go
Add `finalize_zero_amount_invoice` to the organization and customer this was added on this pr  https://github.com/getlago/lago-api/pull/2462
=> Feat(invoice): Feat add skip zero invoices

subscription.go
The goal of this PR is to add current billing period dates at the subscription level.
=> feat: Add current billing period dates

go.mod, go.sum, lago.go, subscription.go
Fixes https://github.com/getlago/lago-go-client/issues/209
This PR makes sure that `GetList` method calls on subscriptions handles correctly multiple status filters
=> fix(subscription): Handle multiple status in GetList

fee.go
Related to https://github.com/getlago/lago-api/pull/2710
Exposes the new `fees#charge_id` field
=> feat(fee): Expose charge_id

invoice.go
This PR adds support for missing invoice statuses
=> add support for missing invoice statuses

billing_period.go, invoice.go
Related to https://github.com/getlago/lago-api/pull/3064
=> feat: Expose billing periods with invoice object

invoice.go, payment.go
=> feat(manual-payments): Add manual payments

wallet.go, wallet_transaction.go
Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feature/` prefixes. Good examples are: `fix/signin-issue` or `feature/issue-templates`.
b. You have a descriptive commit message with a short title (first line).
c. You have only one commit (if not, squash them into one commit).
d. `python3 -m pytest tests` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).
3. **After** these steps, you're ready to open a pull request.
a. Give a descriptive title to your PR.
b. Describe your changes.
c. Put `closes #XXXX` in your comment to auto-close …
=> feat: add new properties to wallet and rules

subscription.go
This PR adds termination / upgrade /downgrade support for invoice preview feature
=> feat (invoice-preview): add support for invoice preview part three

payment_receipt.go
This PR adds payment receipts endpoints
=> feat(payment-receipts): Add payment receipts

payment.go
add NextAction and ExternalCustomerID fields to Payment
=> fix(payment):add params

payment.go
add Metadata field for PaymentResult for pagination
=> fix(payment): add metadata for PaymentResult

.gitignore, invoice.go
Thist PR add the missing `Invoice#void` action
=> feat(invoice): Add missing void action

README.md
This PR adds improve the README by adding information on how to integrate into a project and setup, test and lint in a development environment.
=> docs(README): Improve development documentation

activity_log.go
This PR adds the endpoint to read Activity Logs using the Go client.
=> feat(audit_logs):ActivityLogs endpoints

invoice.go
=> Added params to void invoice

coupon_test.go, credit_note.go, credit_note_test.go, lago_test.go
This PR fixes the `CreditNote()` client to match the Lago Rest API
=> fix(credit_note): Fix all payloads

subscription.go, subscription_test.go, testing/testing.go
This PR also allows `HandlerFunc` to handle `string` mock body.
=> feat(subscription): Allow to terminate subscription without credit note

usage.go
Add endpoint for fetching usages
=> feat(usages): Add usages
